### ISSUE TITLE
i18next - “ WebpackError: TypeError: namespaces.forEach is not a function” (hooks)

### ISSUE THREAD

**Issue by benji011** [benji011/portfolio.benjaminlo.io#6]
## What

There's an issue with setting up `i18next` in this project. You can find more details [in this branch](https://github.com/benji011/portfolio.benjaminlo.io/tree/wip/portfolio-ben-i18n).

To set up the project locally, [please follow this guide](https://github.com/smakosh/gatsby-portfolio-dev/blob/master/README.md) where this project was originally sourced from.

ref: https://stackoverflow.com/questions/64326713/i18next-webpackerror-typeerror-namespaces-foreach-is-not-a-function-hook

**Comment by martink-rsa** [comment]
I would like to try and fix this.

**Comment by benji011** [comment]
Hi @martink-rsa thanks for your interest! If you don't mind then please go for it 👍

Let me know if you have any questions

**Comment by martink-rsa** [comment]
Are you using ESLint? I'm getting a lot of linting errors with the config that is provided:

![image](https://user-images.githubusercontent.com/52622303/95824021-e6fe1500-0d2e-11eb-847e-50b6f202afb7.png)

It's mostly single quotes (`'`) over double quotes (`"`)

**Comment by benji011** [comment]
Ah, I should write this up in the README later.

I use `prettier` to format the entire codebase ( `yarn lint:fix` ). But this was done with its default settings so most likely it switched from single quotes to double quotes by accident which is why you see these lint errors. 

I don't have a custom config file for this yet. But if you like you can add this later & modify as well. Or another formatter is also welcome

**Comment by martink-rsa** [comment]
I'm not experiencing any of the build issues you mentioned and it builds without an issue.

`i18n` wasn't really implemented in the branch you mentioned, I think you might have deleted it so you could keep working?

I added the `i18n` dependencies back to the project, as well as added `ToggleLanguage` to the header.

I then had the error of `i18n.language` being undefined because of this line:

![image](https://user-images.githubusercontent.com/52622303/95828759-a81f8d80-0d35-11eb-9036-feb97d71b5c5.png)

That was expeted though because the app wasn't using the Provider yet. I then wrapped Page `index.js` contents in the provider:

![image](https://user-images.githubusercontent.com/52622303/95828913-dc934980-0d35-11eb-933e-b2c85f7368f8.png)

It now doesn't have an error, and if I log `i18n` in the `ToggleLanguage` file, I can see your English and Japanese data objects in the `store`: 

![image](https://user-images.githubusercontent.com/52622303/95829160-2ed46a80-0d36-11eb-8f11-ebe008d87ae1.png)

Unfortunately, the main languages object only mentions `english` and `dev` though so I think i18n maybe has a misconfiguration? 

![image](https://user-images.githubusercontent.com/52622303/95829261-4f042980-0d36-11eb-86de-33ad97b6290e.png)

**Comment by benji011** [comment]
@martink-rsa Wow thanks for the quick response! That .. is interesting. In that case, if it's not too much trouble can you create a pull request to `portfolio-ben-i18n` ? (You don't need to load the actual i18n files into the source as long as the provider is added).

If all looks good i'll merge it as soon as i take a look

**Comment by martink-rsa** [comment]
Sure, no problem!

As a side note, you should check to see if you have the ESLint (linting tool) plugin installed in VSCode (presuming you use this editor). There is an ESLint config file in the project that comes with the Gatsby starter project, but this ruleset for some reason isn't being followed. It might be that ESLint is not installed. 

If you want to discuss it more, you can email me at martin@martinkruger.com or we can chat over Slack/Discord.

**Comment by martink-rsa** [comment]
Here is the PR: https://github.com/benji011/portfolio.benjaminlo.io/pull/9. Please let me know if that's the incorrect branch. I've changed it from the `wip` one to `portfolio-ben-no-i18n` .

**Comment by benji011** [comment]
Thank you @martink-rsa for the solid contribution & kind advice regarding ESLint! This issue is now resolved

**Comment by martink-rsa** [comment]
No problem! I'm a web dev mentor so if you ever need help don't hesitate to ask! Keep well.
